#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    environment:
        # Customize the JVM maximum heap limit
        JVM_OPTS: -Xmx3200m
        TERM: dumb
        CC_TEST_REPORTER_ID: a39e969cb57292d7b07afeaf6a2098bae2f5d855879d488f3d825f282f9e09b6
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run:
          name: Build and run test
          command: |
            gradle clean build jacocoTestReport;
      - run:
          name: Upload Code Coverage to CodeClimate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            mkdir -p artifacts/core;cp -af core/build/reports/* artifacts/core;
            mkdir -p /home/circleci/repo/test-results/core;cp -af core/build/reports/* /home/circleci/repo/test-results/core;
            mkdir -p coverage
            JACOCO_SOURCE_PATH=core/src/main/java ./cc-test-reporter format-coverage core/build/reports/jacoco/jacoco.xml --input-type jacoco --output coverage/codeclimate.core.json;
            ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
            ./cc-test-reporter upload-coverage  --input coverage/codeclimate.json
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results:
          path: test-results
